M48
; DRILL file {KiCad 9.0.6} date 2025-12-14T15:20:11+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-14T15:20:11+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X48.5Y-53.0
X48.5Y-75.5
X126.5Y-53.0
X127.0Y-75.5
M30
